"""Añadir Columna Peso

Revision ID: d106b3393ef7
Revises: de3dad1e7bad
Create Date: 2024-06-26 12:34:16.451831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd106b3393ef7'
down_revision = 'de3dad1e7bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_kgs', sa.Numeric(precision=16, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envio', schema=None) as batch_op:
        batch_op.drop_column('peso_kgs')

    # ### end Alembic commands ###
